package safe.com.gamehuber.mvp.model.bean

data class HomeBannerBean(
        val adCode: String,
        val adName: String,
        val adWeight: Int,
        val adspaceDescription: String,
        val adspaceId: String,
        val adspaceName: String,
        val category: String,
        val chargeAmount: Double,
        val chargeMode: Int,
        val clickCount: Int,
        val cover: Any,
        val createTime: String,
        val deleted: Boolean,
        val desc: Any,
        val displayCount: Int,
        val endTime: String,
        val icon: Any,
        val id: String,
        val imageUrl: String,
        val isEnabled: Boolean,
        val isEnabledStr: String,
        val ownerName: String,
        val price: Any,
        val siteId: String,
        val startTime: String,
        val title: String,
        val topicId: String,
        val updateTime: String,
        val userId: Any,
        val videoUrl: Any,
        val wesiteUrl: Any
)